{
  "hash": "1ba598c7f119297024264543ffcd16a7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Models II: Linear Models in Ag-Data Science\"\nauthor: \"Dr. Adrian Correndo\"\ndate: \"2026-02-25\"\ncategories: [linear models, R, statistics, agriculture]\nformat:\n  html:\n    toc: true\n    toc-location: left\n    toc-depth: 4\n    number-sections: true\n    table-class: \"table table-striped table-hover\"\neditor: source\nexecute:\n  echo: true\n  warning: false\n  message: false\nsmooth-scroll: true\n---\n\n\n\n\n## Introduction\n\nLinear models (LMs) are the workhorse for inference in agronomy: they connect field designs (blocks, treatments, sites, years) to estimable effects, standard errors, and tests of hypotheses.\n\nThat said, many agronomic datasets are not well represented by a single fixed-effect LM. Yield responses to inputs can be curved (non-linear), site-by-year variability can be large, and error structures can be non-independent (blocks, split-plots, repeated measures) or heteroscedastic. This document focuses on **linear models as a baseline**, while using plots to show where the baseline becomes too simple.\n\n:::callout-note\n## Why start with linear models?\nEven when the final model is a mixed model or a non-linear model, a well-posed linear model is still useful to:\n\n- define the estimands (means, contrasts, slopes)\n- diagnose data issues (outliers, leverage, heteroscedasticity)\n- communicate the direction and magnitude of effects\n:::\n\n## What is a Linear Model?\n\nA linear model can be written in two equivalent ways.\n\n### Scalar form\n\n$$Y_i = \\beta_0 + \\beta_1 X_{i1} + \\beta_2 X_{i2} + \\cdots + \\beta_p X_{ip} + \\varepsilon_i$$\n\n- $Y_i$: response for observation $i$ (for example, yield)\n- $X_{ij}$: predictor $j$ for observation $i$ (continuous values or columns created from factor levels via contrasts)\n- $\\beta_j$: unknown parameters (effects) to estimate\n- $\\varepsilon_i$: error term (unexplained variation)\n\n### Matrix form\n\nThis is the most compact way to express a linear model and is the language behind ANOVA tables and regression.\n\n$$\\mathbf{y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\varepsilon}$$\n\nThis representation matters in experiments because ANOVA and regression use the same linear-model framework.\n\n- **X** comes from your data table: it is the model (design) matrix containing the explanatory variables as used by the model (including columns created by factor coding, contrasts, and interactions).\n- **beta** is the vector of effects/parameters attached to those columns (for example, treatment effects, block effects, site effects).\n\nIn other words, your **experimental design** determines how the explanatory variables are encoded into X, and therefore what each element of beta represents.\n\n:::callout-note\n## Linear in parameters\nA polynomial term (quadratic, cubic) changes the *shape* of the relationship but remains a linear model because the model is still linear in the parameters $\\beta$.\n:::\n\n## Regression vs. ANOVA\n\nSame engine, different questions.\n\n- **Regression**: at least one explanatory variable is continuous (for example, yield vs nitrogen rate).\n- **ANOVA**: at least one predictor is categorical (for example, treatment means).\n\nBoth are solved by the same least squares machinery; the main difference is **how we encode predictors** and **what we interpret** (slopes vs means/contrasts).\n\n## Packages\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(pacman)\n\n# Data manipulation\np_load(dplyr, tidyr)\n\n# Model summaries and inference\np_load(broom)\np_load(car)\np_load(emmeans, multcomp, multcompView)\n\n# Diagnostics\np_load(performance)\n\n# Plotting\np_load(ggplot2)\n```\n:::\n\n\n\n\n## Data\n\nWe will use a synthetic dataset of corn yield response to nitrogen fertilizer across two sites and three years with contrasting weather.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read CSV file\ncornn_data <- read.csv(\"data/cornn_data.csv\") %>%\n  mutate(n_trt = factor(n_trt, levels = c(\"N0\",\"N60\",\"N90\",\"N120\",\n                                          \"N180\",\"N240\",\"N300\")),\n         block = factor(block),\n         site = factor(site),\n         year = factor(year),\n         weather = factor(weather)  ) %>% \n  mutate(yield_tha = yield_kgha / 1000)\n\nglimpse(cornn_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 168\nColumns: 8\n$ site       <fct> A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A,…\n$ year       <fct> 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004,…\n$ block      <fct> 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4,…\n$ n_trt      <fct> N0, N0, N0, N0, N60, N60, N60, N60, N90, N90, N90, N90, N12…\n$ nrate_kgha <int> 0, 0, 0, 0, 60, 60, 60, 60, 90, 90, 90, 90, 120, 120, 120, …\n$ yield_kgha <int> 6860, 7048, 8083, 8194, 10010, 9568, 10256, 10939, 11959, 1…\n$ weather    <fct> normal, normal, normal, normal, normal, normal, normal, nor…\n$ yield_tha  <dbl> 6.860, 7.048, 8.083, 8.194, 10.010, 9.568, 10.256, 10.939, …\n```\n\n\n:::\n:::\n\n\n\n\n## Misc\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset_theme(theme_classic())\n```\n:::\n\n\n\n\n:::callout-note\n## Variable convention\nThis document uses `block` consistently as the blocking factor. If your dataset uses `rep` instead, update the code accordingly.\n:::\n\n## Exploratory Data Analysis\n\n### Quick view\n\nHere we treat nitrogen rate as a categorical treatment and compare yield distributions across levels.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neda_box <- cornn_data %>%\n  ggplot(aes(x = n_trt, y = yield_tha)) +\n  geom_boxplot(aes(fill = n_trt)) +\n  scale_fill_brewer(palette = \"Set3\") +\n  labs(title = \"Yield by N treatment\",\n       x = \"Nitrogen treatment\",\n       y = \"Corn yield (Mg/ha)\")+\n  scale_y_continuous(breaks = seq(0,18,by=2))\n\neda_box\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n### Yield vs nitrogen rate\n\nHere we treat nitrogen rate as a continuous explanatory variable and visualize the average trend with a simple linear fit.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neda_scatter <- cornn_data %>%\n  ggplot(aes(x = nrate_kgha, y = yield_kgha)) +\n  geom_point(alpha = 0.7, shape = 21, fill = \"orange\", size = 1.5) +\n  geom_smooth(method = \"lm\", se = FALSE, linetype = 2, color = \"black\") +\n  labs(title = \"Yield response (pooled): linear fit\",\n    x = \"Nitrogen rate (kg/ha)\",\n    y = \"Corn yield (kg/ha)\")+\n  scale_y_continuous(breaks = seq(0,18,by=2))+\n  scale_x_continuous(breaks = seq(0,300,by=50))+\n  ggpubr::stat_regline_equation(method = \"lm\", \n                      label.x.npc = \"left\", label.y.npc = \"top\", label.sep = \"\\n\")\n\neda_scatter\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n### Heterogeneity across environments\n\nHere we split the data by site and year to see whether the yield response pattern changes across environments.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neda_scatter_env <- cornn_data %>%\n  ggplot(aes(x = nrate_kgha, y = yield_tha)) +\n  geom_point(alpha = 0.7, shape = 21, fill = \"orange\", size = 1.5) +\n  geom_smooth(method = \"lm\", se = FALSE, linetype = 2, color = \"black\") +\n  facet_grid(site ~ weather) +\n  labs(title = \"Yield response by environment (site x year): linear fits\",\n    x = \"Nitrogen rate (kg/ha)\",\n    y = \"Corn yield (Mg/ha)\")+\n  scale_y_continuous(breaks = seq(0,18,by=2))+\n  scale_x_continuous(breaks = seq(0,300,by=50))\n\neda_scatter_env\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n:::callout-note\n## What to look for in these plots\n- Different slopes by site or year (suggests interactions or varying coefficients)\n- Curvature (suggests polynomial terms or non-linear models)\n- Different spread by environment or N rate (suggests heteroscedasticity)\n:::\n\n## Model Fitting: Linear Regression and ANOVA\n\n### Simple linear regression\n\nWe start with a pooled model that estimates one average slope across all environments.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_fit <- lm(yield_kgha ~ 1 + nrate_kgha, data = cornn_data)\nsummary(reg_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yield_kgha ~ 1 + nrate_kgha, data = cornn_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8424.1 -2984.2  -251.2  2596.0  6117.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 7676.634    438.308   17.51  < 2e-16 ***\nnrate_kgha    19.158      2.554    7.50 3.66e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3217 on 166 degrees of freedom\nMultiple R-squared:  0.2531,\tAdjusted R-squared:  0.2486 \nF-statistic: 56.25 on 1 and 166 DF,  p-value: 3.658e-12\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(reg_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: yield_kgha\n            Df     Sum Sq   Mean Sq F value    Pr(>F)    \nnrate_kgha   1  582135209 582135209   56.25 3.658e-12 ***\nResiduals  166 1717930697  10348980                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::Anova(reg_fit, type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type II tests)\n\nResponse: yield_kgha\n               Sum Sq  Df F value    Pr(>F)    \nnrate_kgha  582135209   1   56.25 3.658e-12 ***\nResiduals  1717930697 166                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::Anova(reg_fit, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: yield_kgha\n                Sum Sq  Df F value    Pr(>F)    \n(Intercept) 3174537867   1  306.75 < 2.2e-16 ***\nnrate_kgha   582135209   1   56.25 3.658e-12 ***\nResiduals   1717930697 166                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n### Why a simple model can look good\n\nA statistically significant slope can still be a poor scientific summary if responses differ by environment.\n\nA single slope forces one response pattern across all sites and years.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare pooled fit vs environment-specific fits visually\ncornn_data %>%\n  ggplot(aes(x = nrate_kgha, y = yield_tha)) +\n  geom_point(alpha = 0.7, size = 1.5,\n             aes(fill=site, shape=site)) +\n  # Fit by panel\n  geom_smooth(method = \"lm\", se = FALSE, linetype = 2, color = \"black\") +\n  geom_smooth(aes(color = site), method = \"lm\", se = FALSE) +\n  facet_wrap(~ weather) +\n  scale_shape_manual(values = c(21, 22, 23), name = \"site\") +\n  scale_fill_brewer(palette = \"Set2\", name = \"site\") +\n  scale_color_brewer(palette = \"Set2\", name = \"site\") +\n  labs(title = \"Pooled vs site-specific linear trends (by year)\",\n    x = \"Nitrogen rate (kg/ha)\",\n    y = \"Corn yield (Mg/ha)\")+\n  scale_y_continuous(breaks = seq(0,18,by=2))+\n  scale_x_continuous(breaks = seq(0,300,by=50))\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n:::callout-note\n## Interpretation\nIf site-specific lines differ meaningfully from the pooled line, a single fixed slope is a poor summary of the process, even if the pooled model has significant p-values or a respectable R^2^.\n:::\n\n### Linear regression\n\nThis variant forces the fitted line through the origin, which is rarely justified in agronomy.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_noint <- lm(yield_kgha ~ -1 + nrate_kgha, data = cornn_data)\nsummary(reg_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yield_kgha ~ 1 + nrate_kgha, data = cornn_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8424.1 -2984.2  -251.2  2596.0  6117.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 7676.634    438.308   17.51  < 2e-16 ***\nnrate_kgha    19.158      2.554    7.50 3.66e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3217 on 166 degrees of freedom\nMultiple R-squared:  0.2531,\tAdjusted R-squared:  0.2486 \nF-statistic: 56.25 on 1 and 166 DF,  p-value: 3.658e-12\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(reg_noint)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yield_kgha ~ -1 + nrate_kgha, data = cornn_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11809.8   -303.7   3197.5   6720.5   9758.1 \n\nCoefficients:\n           Estimate Std. Error t value Pr(>|t|)    \nnrate_kgha   56.033      2.434   23.02   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5413 on 167 degrees of freedom\nMultiple R-squared:  0.7604,\tAdjusted R-squared:  0.759 \nF-statistic: 530.1 on 1 and 167 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(reg_noint)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: yield_kgha\n            Df     Sum Sq    Mean Sq F value    Pr(>F)    \nnrate_kgha   1 1.5530e+10 1.5530e+10   530.1 < 2.2e-16 ***\nResiduals  167 4.8925e+09 2.9296e+07                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::Anova(reg_noint, type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type II tests)\n\nResponse: yield_kgha\n               Sum Sq  Df F value    Pr(>F)    \nnrate_kgha 1.5530e+10   1   530.1 < 2.2e-16 ***\nResiduals  4.8925e+09 167                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::Anova(reg_noint, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: yield_kgha\n               Sum Sq  Df F value    Pr(>F)    \nnrate_kgha 1.5530e+10   1   530.1 < 2.2e-16 ***\nResiduals  4.8925e+09 167                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n:::callout-note\n## When does a no-intercept model make sense?\nRarely for agronomy. It implies the expected response is exactly 0 when N rate is 0 (or when all predictors are 0). Use it only when that constraint is scientifically justified.\n:::\n\n### ANOVA\n\nHere we treat nitrogen as a categorical factor and estimate treatment means (and blocks if included).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CRD (ignoring blocks)\nanova_crd <- lm(yield_kgha ~ n_trt, data = cornn_data)\n\n# RCBD (blocks as fixed effect in lm)\nanova_rcbd <- lm(yield_kgha ~ n_trt + block, data = cornn_data)\n\n# Treatment by block interaction (usually not desired as a model, but shown for illustration)\nanova_trt_block <- lm(yield_kgha ~ n_trt * block, data = cornn_data)\n\ncar::Anova(anova_crd, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: yield_kgha\n                Sum Sq  Df F value    Pr(>F)    \n(Intercept)  862968308   1  92.663 < 2.2e-16 ***\nn_trt        800679144   6  14.329 4.687e-13 ***\nResiduals   1499386761 161                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::Anova(anova_rcbd, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: yield_kgha\n                Sum Sq  Df F value    Pr(>F)    \n(Intercept)  669823217   1 70.8934 2.155e-14 ***\nn_trt        800679144   6 14.1238 7.656e-13 ***\nblock          6553460   3  0.2312    0.8745    \nResiduals   1492833301 158                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::Anova(anova_trt_block, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: yield_kgha\n                Sum Sq  Df F value    Pr(>F)    \n(Intercept)  221701131   1 21.1557 9.385e-06 ***\nn_trt        225093237   6  3.5799  0.002485 ** \nblock          2709898   3  0.0862  0.967497    \nn_trt:block   25706084  18  0.1363  0.999992    \nResiduals   1467127217 140                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n### ANOVA\n\nThis parameterization estimates a mean for each treatment level directly (useful for interpretation), while still representing the same fitted values as the intercept model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_noint <- lm(yield_kgha ~ -1 + n_trt + block, data = cornn_data)\ncar::Anova(anova_noint, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: yield_kgha\n              Sum Sq  Df F value Pr(>F)    \nn_trt     5612876425   7 84.8659 <2e-16 ***\nblock        6553460   3  0.2312 0.8745    \nResiduals 1492833301 158                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(anova_rcbd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yield_kgha ~ n_trt + block, data = cornn_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6777.3 -2784.1   110.9  2617.3  5560.5 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   6314.3      749.9   8.420 2.16e-14 ***\nn_trtN60      2520.7      887.3   2.841  0.00509 ** \nn_trtN90      4257.5      887.3   4.798 3.68e-06 ***\nn_trtN120     5542.7      887.3   6.246 3.72e-09 ***\nn_trtN180     6049.9      887.3   6.818 1.85e-10 ***\nn_trtN240     6396.7      887.3   7.209 2.19e-11 ***\nn_trtN300     5960.5      887.3   6.717 3.17e-10 ***\nblock2        -305.9      670.8  -0.456  0.64898    \nblock3        -468.1      670.8  -0.698  0.48627    \nblock4        -497.5      670.8  -0.742  0.45935    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3074 on 158 degrees of freedom\nMultiple R-squared:  0.351,\tAdjusted R-squared:  0.314 \nF-statistic: 9.493 on 9 and 158 DF,  p-value: 1.707e-11\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(anova_noint)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yield_kgha ~ -1 + n_trt + block, data = cornn_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6777.3 -2784.1   110.9  2617.3  5560.5 \n\nCoefficients:\n          Estimate Std. Error t value Pr(>|t|)    \nn_trtN0     6314.3      749.9   8.420 2.16e-14 ***\nn_trtN60    8835.0      749.9  11.781  < 2e-16 ***\nn_trtN90   10571.8      749.9  14.097  < 2e-16 ***\nn_trtN120  11857.0      749.9  15.811  < 2e-16 ***\nn_trtN180  12364.2      749.9  16.487  < 2e-16 ***\nn_trtN240  12711.1      749.9  16.950  < 2e-16 ***\nn_trtN300  12274.8      749.9  16.368  < 2e-16 ***\nblock2      -305.9      670.8  -0.456    0.649    \nblock3      -468.1      670.8  -0.698    0.486    \nblock4      -497.5      670.8  -0.742    0.459    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3074 on 158 degrees of freedom\nMultiple R-squared:  0.9269,\tAdjusted R-squared:  0.9223 \nF-statistic: 200.4 on 10 and 158 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n## Model Assumptions\n\nThis checklist is the standard set of assumptions behind least squares inference. Some items can be assessed with formal tests, but most are evaluated using residual plots plus knowledge of the experimental design and error structure.\n\n### 1) Linearity\n\nFor continuous explanatory variables, the mean response should be approximately linear in the predictors as specified (given the terms you include in the model, such as interactions or polynomial terms).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Residual plot for regression\nplot(reg_fit, which = 1)\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\n### 2) Normality of residuals\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Normal Q-Q plot\nplot(reg_fit, which = 2)\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Formal test (sensitive to large n)\nshapiro.test(resid(reg_fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  resid(reg_fit)\nW = 0.96023, p-value = 0.0001013\n```\n\n\n:::\n:::\n\n\n\n\n### 3) Homoscedasticity\n\nResidual variance should be approximately constant across fitted values and across groups of interest.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Levene tests are common for simple fixed-effect ANOVA settings\ncar::leveneTest(yield_kgha ~ n_trt, data = cornn_data)\n\n# You can also apply Levene-type ideas to residuals from a fixed-effect lm\ncar::leveneTest(resid(reg_fit) ~ cornn_data$n_trt)\n```\n:::\n\n\n\n\n:::callout-note\n## Practical limitations of Levene tests\n- Levene tests are most useful in simple fixed-effect ANOVA contexts (for example, one-way or two-way ANOVA).\n- In mixed models, the relevant question is often whether the **residual variance** is homogeneous after accounting for random effects and the covariance structure. A vanilla Levene test on raw data (or on lm residuals) does not answer that question.\n- Levene tests are sensitive to sample size: with large n, tiny variance differences can be statistically significant but practically irrelevant; with small n, the test can have low power.\n\nIn practice, prefer combining (1) residual plots by groups and fitted values, and (2) model-based approaches (for example, specifying a variance function or group-specific residual variance in an appropriate model) when heteroscedasticity matters.\n:::\n\n### 4) Independence\n\nThere is no universal \"independence test\" that fixes a design problem. Independence is addressed by:\n\n- the design (randomization and blocking)\n- the appropriate error structure (mixed models, repeated measures models, spatial correlation)\n\n### 5) One-stop diagnostics\n\nWe can run a compact set of diagnostic checks (residual distribution, heteroscedasticity signals, influential points) using the `performance` package. Treat these plots as *screening tools* to guide what you look at next, not as a substitute for understanding the design and the error structure.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_model(anova_rcbd)\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-15-1.png){width=768}\n:::\n:::\n\n\n\n\n:::callout-note\n## Practical rule\nIf diagnostics show strong curvature, heteroscedasticity, or environment-specific patterns, treat your LM as a baseline, not as the final model.\n:::\n\n## Model Building: Fixed-effect candidates\n\nThese are all fixed-effect models. They are useful for learning and for baseline comparisons.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Null model\nlm_00 <- lm(yield_kgha ~ 1, data = cornn_data)\n\n# Treatment + block\nlm_01 <- lm(yield_kgha ~ n_trt + block, data = cornn_data)\n\n# Add site\nlm_02 <- lm(yield_kgha ~ n_trt + site + block, data = cornn_data)\n\n# Add weather\nlm_03 <- lm(yield_kgha ~ n_trt + weather + block, data = cornn_data)\n\n# Add site and weather\nlm_04 <- lm(yield_kgha ~ n_trt + site + weather + block, data = cornn_data)\n\n# Main effects and interactions\nlm_05 <- lm(yield_kgha ~ n_trt * site * weather + block, data = cornn_data)\n```\n:::\n\n\n\n\n## Model Selection: nested F-tests and information criteria\n\nWe often compare multiple candidate models for the *same response variable* to balance fit and parsimony. In agronomy, model selection is not a substitute for thinking about design and biology; it is a tool to compare plausible alternatives.\n\n\n### Nested F-tests\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(lm_01, lm_02, lm_03, lm_04, lm_05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: yield_kgha ~ n_trt + block\nModel 2: yield_kgha ~ n_trt + site + block\nModel 3: yield_kgha ~ n_trt + weather + block\nModel 4: yield_kgha ~ n_trt + site + weather + block\nModel 5: yield_kgha ~ n_trt * site * weather + block\n  Res.Df        RSS Df  Sum of Sq         F    Pr(>F)    \n1    158 1492833301                                      \n2    157 1444009602  1   48823699   46.6647 3.443e-10 ***\n3    156  391188885  1 1052820717 1006.2652 < 2.2e-16 ***\n4    155  342365186  1   48823699   46.6647 3.443e-10 ***\n5    123  128690677 32  213674509    6.3821 2.304e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n### AIC and BIC\n\nAIC and BIC are likelihood-based criteria that trade off goodness-of-fit against model complexity.\n\n- **AIC** tends to favor models with better predictive performance (it penalizes complexity, but less strongly).\n- **BIC** penalizes complexity more strongly and tends to select simpler models as sample size increases.\n\n:::callout-note\n## Interpreting differences (rule-of-thumb)\nUse **delta** values (differences from the best, lowest-criterion model). Avoid translating deltas into simple \"percent support\". The useful comparison is the *magnitude of the delta* relative to the best model.\n\nA commonly cited rule-of-thumb (Anderson, 2008) is:\n\n- Δ close to 0: strong empirical support\n- Δ in the rough range 4 to 7: considerably less support\n- Δ in the fringes (about 9 to 14): relatively little support\n\nImportant nuance (also emphasized by Anderson, 2008, Chapter 4): the old classroom rule \"ΔAIC > 2 means dismiss the model\" is too aggressive. Models with Δ around 2, 4, or even 6 to 7 can still have meaningful support and should not be automatically discarded.\n\nWhere Δ is the difference from the minimum AIC (or AICc) within the candidate set.\n:::\n\n:::callout-note\n## Pros and cons in practice\n**Pros**\n- Provides a simple way to compare multiple candidate models, not only nested ones.\n- Encourages parsimony (guards against overfitting).\n\n**Cons / limitations**\n- AIC/BIC comparisons are valid only when models are fit to the **same response variable on the same scale** and using the **same data**. Do not compare models fit to different transformations (for example, yield vs log(yield)) using raw AIC/BIC values.\n- These criteria assume the likelihood is comparable across models. If you change the error model, use different variance structures, or fit models with different likelihood definitions, interpret comparisons cautiously.\n- In unbalanced multi-environment datasets, AIC/BIC may favor statistically convenient models that still miss key biological structure (for example, varying response curves by environment).\n\nPractical workflow: use AIC/BIC to rank *plausible* models, then confirm adequacy with diagnostics and scientific interpretability.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(lm_01, lm_02, lm_03, lm_04, lm_05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      df      AIC\nlm_01 11 3186.760\nlm_02 12 3183.173\nlm_03 13 2965.767\nlm_04 14 2945.371\nlm_05 46 2844.988\n```\n\n\n:::\n\n```{.r .cell-code}\nBIC(lm_01, lm_02, lm_03, lm_04, lm_05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      df      BIC\nlm_01 11 3221.123\nlm_02 12 3220.661\nlm_03 13 3006.379\nlm_04 14 2989.106\nlm_05 46 2988.691\n```\n\n\n:::\n\n```{.r .cell-code}\n# Optional: compute deltas relative to the best model in the set\ncrit_tbl <- tibble(\n  model = c(\"lm_01\",\"lm_02\",\"lm_03\",\"lm_04\",\"lm_05\"),\n  AIC = c(AIC(lm_01), AIC(lm_02), AIC(lm_03), AIC(lm_04), AIC(lm_05)),\n  BIC = c(BIC(lm_01), BIC(lm_02), BIC(lm_03), BIC(lm_04), BIC(lm_05))\n) %>%\n  mutate(\n    dAIC = AIC - min(AIC),\n    dBIC = BIC - min(BIC)\n  ) %>%\n  arrange(AIC)\n\ncrit_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  model   AIC   BIC  dAIC    dBIC\n  <chr> <dbl> <dbl> <dbl>   <dbl>\n1 lm_05 2845. 2989.    0    0    \n2 lm_04 2945. 2989.  100.   0.415\n3 lm_03 2966. 3006.  121.  17.7  \n4 lm_02 3183. 3221.  338. 232.   \n5 lm_01 3187. 3221.  342. 232.   \n```\n\n\n:::\n:::\n\n\n\n\n:::callout-note\n## Caveat\nAIC/BIC comparisons depend on the likelihood assumptions. With clear heteroscedasticity or correlation, these criteria can favor models that are statistically convenient rather than scientifically adequate.\n:::\n\n## Significance of effects\n\nType II and Type III tests answer different questions when interactions are present, so you should match the test to your inferential goal.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::Anova(lm_05, type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type II tests)\n\nResponse: yield_kgha\n                       Sum Sq  Df  F value    Pr(>F)    \nn_trt               800679144   6 127.5455 < 2.2e-16 ***\nsite                 48823699   1  46.6647 3.443e-10 ***\nweather            1101644416   2 526.4650 < 2.2e-16 ***\nblock                 6553460   3   2.0879    0.1053    \nn_trt:site           32240563   6   5.1358 9.665e-05 ***\nn_trt:weather        88856968  12   7.0773 1.131e-09 ***\nsite:weather         79885562   2  38.1765 1.266e-13 ***\nn_trt:site:weather   12691415  12   1.0109    0.4432    \nResiduals           128690677 123                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::Anova(lm_05, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: yield_kgha\n                      Sum Sq  Df  F value    Pr(>F)    \n(Intercept)        122656903   1 117.2330 < 2.2e-16 ***\nn_trt               36106271   6   5.7516 2.649e-05 ***\nsite                 5502903   1   5.2596  0.023524 *  \nweather             10451960   2   4.9949  0.008210 ** \nblock                6553460   3   2.0879  0.105268    \nn_trt:site           8426862   6   1.3424  0.243500    \nn_trt:weather       61367142  12   4.8878 1.498e-06 ***\nsite:weather        11037465   2   5.2747  0.006341 ** \nn_trt:site:weather  12691415  12   1.0109  0.443194    \nResiduals          128690677 123                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n:::callout-note\n## Interpretation tip\n- Type II is commonly used for models with interactions when the goal is marginal tests of main effects (under hierarchy).\n- Type III tests each term given all other terms (including interactions), which can be useful but is more sensitive to coding and balance.\n:::\n\n## Means Comparisons with `emmeans` and `cld`\n\n### Interaction means\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(lm_05, pairwise ~ n_trt:weather) %>%\n  cld(., level = 0.05, decreasing = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n n_trt weather emmean  SE  df lower.CL upper.CL .group    \n N240  wet      16232 362 123    16210    16255  1        \n N300  wet      15851 362 123    15828    15873  1        \n N180  wet      15742 362 123    15719    15764  1        \n N120  wet      15080 362 123    15058    15103  12       \n N90   wet      13571 362 123    13548    13593   23      \n N240  normal   12445 362 123    12422    12468    34     \n N180  normal   12247 362 123    12224    12270    34     \n N120  normal   11886 362 123    11863    11908    34     \n N300  normal   11312 362 123    11290    11335     45    \n N60   wet      11213 362 123    11190    11236     45    \n N90   normal    9800 362 123     9777     9822      56   \n N300  dry       8708 362 123     8685     8730       67  \n N240  dry       8502 362 123     8479     8525       67  \n N60   normal    8172 362 123     8149     8195       67  \n N180  dry       8150 362 123     8128     8173       67  \n N120  dry       7652 362 123     7629     7674        78 \n N90   dry       7392 362 123     7369     7414        78 \n N0    wet       7352 362 123     7329     7374        78 \n N60   dry       6166 362 123     6143     6189         89\n N0    normal    6053 362 123     6030     6076         89\n N0    dry       4585 362 123     4562     4607          9\n\nResults are averaged over the levels of: site, block \nConfidence level used: 0.05 \nP value adjustment: tukey method for comparing a family of 21 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n\n\n### Same model, different slicing\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(lm_05, pairwise ~ n_trt, by = \"weather\") %>%\n  cld(., level = 0.05, decreasing = TRUE, Letters = letters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nweather = dry:\n n_trt emmean  SE  df lower.CL upper.CL .group\n N300    8708 362 123     8685     8730  a    \n N240    8502 362 123     8479     8525  a    \n N180    8150 362 123     8128     8173  a    \n N120    7652 362 123     7629     7674  ab   \n N90     7392 362 123     7369     7414  ab   \n N60     6166 362 123     6143     6189   b   \n N0      4585 362 123     4562     4607    c  \n\nweather = normal:\n n_trt emmean  SE  df lower.CL upper.CL .group\n N240   12445 362 123    12422    12468  a    \n N180   12247 362 123    12224    12270  a    \n N120   11886 362 123    11863    11908  a    \n N300   11312 362 123    11290    11335  ab   \n N90     9800 362 123     9777     9822   b   \n N60     8172 362 123     8149     8195    c  \n N0      6053 362 123     6030     6076     d \n\nweather = wet:\n n_trt emmean  SE  df lower.CL upper.CL .group\n N240   16232 362 123    16210    16255  a    \n N300   15851 362 123    15828    15873  a    \n N180   15742 362 123    15719    15764  a    \n N120   15080 362 123    15058    15103  ab   \n N90    13571 362 123    13548    13593   b   \n N60    11213 362 123    11190    11236    c  \n N0      7352 362 123     7329     7374     d \n\nResults are averaged over the levels of: site, block \nConfidence level used: 0.05 \nP value adjustment: tukey method for comparing a family of 7 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n\n```{.r .cell-code}\nLETTERS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"A\" \"B\" \"C\" \"D\" \"E\" \"F\" \"G\" \"H\" \"I\" \"J\" \"K\" \"L\" \"M\" \"N\" \"O\" \"P\" \"Q\" \"R\" \"S\"\n[20] \"T\" \"U\" \"V\" \"W\" \"X\" \"Y\" \"Z\"\n```\n\n\n:::\n\n```{.r .cell-code}\nletters\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"a\" \"b\" \"c\" \"d\" \"e\" \"f\" \"g\" \"h\" \"i\" \"j\" \"k\" \"l\" \"m\" \"n\" \"o\" \"p\" \"q\" \"r\" \"s\"\n[20] \"t\" \"u\" \"v\" \"w\" \"x\" \"y\" \"z\"\n```\n\n\n:::\n:::\n\n\n\n\n## Interpreting coefficients\n\n### Regression\n\n- **Intercept ($\\beta_0$)**: expected value of $Y$ when $X = 0$.\n- **Slope ($\\beta_1$)**: change in expected $Y$ per unit change in $X$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(reg_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  nrate_kgha \n  7676.6337     19.1581 \n```\n\n\n:::\n\n```{.r .cell-code}\nreg_coefs <- broom::tidy(reg_fit)\nreg_coefs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   7677.     438.       17.5  1.44e-39\n2 nrate_kgha      19.2      2.55      7.50 3.66e-12\n```\n\n\n:::\n:::\n\n\n\n\n### ANOVA\n\n- **Intercept**: reference level mean (baseline) under the default contrasts.\n- **Factor levels**: differences relative to the reference level.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm_05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  (Intercept)                      n_trtN60 \n                    5731.8869                     1949.2500 \n                     n_trtN90                     n_trtN120 \n                    3095.2500                     2836.5000 \n                    n_trtN180                     n_trtN240 \n                    2988.2500                     3278.2500 \n                    n_trtN300                         siteB \n                    3581.2500                    -1658.7500 \n                weathernormal                    weatherwet \n                    2132.2500                     1780.0000 \n                       block2                        block3 \n                    -305.9048                     -468.1190 \n                       block4                n_trtN60:siteB \n                    -497.5238                     -735.5000 \n               n_trtN90:siteB               n_trtN120:siteB \n                    -576.7500                      460.7500 \n              n_trtN180:siteB               n_trtN240:siteB \n                    1154.7500                     1278.5000 \n              n_trtN300:siteB        n_trtN60:weathernormal \n                    1083.7500                      697.7500 \n       n_trtN90:weathernormal       n_trtN120:weathernormal \n                    1122.0000                     3277.0000 \n      n_trtN180:weathernormal       n_trtN240:weathernormal \n                    2909.5000                     2735.0000 \n      n_trtN300:weathernormal           n_trtN60:weatherwet \n                     -74.2500                     1807.5000 \n          n_trtN90:weatherwet          n_trtN120:weatherwet \n                    3474.5000                     4625.2500 \n         n_trtN180:weatherwet          n_trtN240:weatherwet \n                    5424.5000                     4865.0000 \n         n_trtN300:weatherwet           siteB:weathernormal \n                    4300.0000                    -1327.5000 \n             siteB:weatherwet  n_trtN60:siteB:weathernormal \n                    1973.7500                     -320.5000 \n n_trtN90:siteB:weathernormal n_trtN120:siteB:weathernormal \n                    -365.0000                    -1023.0000 \nn_trtN180:siteB:weathernormal n_trtN240:siteB:weathernormal \n                    -562.2500                     -521.5000 \nn_trtN300:siteB:weathernormal     n_trtN60:siteB:weatherwet \n                    2421.0000                      945.0000 \n    n_trtN90:siteB:weatherwet    n_trtN120:siteB:weatherwet \n                    -124.2500                       73.5000 \n   n_trtN180:siteB:weatherwet    n_trtN240:siteB:weatherwet \n                   -1200.2500                      197.0000 \n   n_trtN300:siteB:weatherwet \n                     152.0000 \n```\n\n\n:::\n\n```{.r .cell-code}\nanova_coefs <- broom::tidy(lm_05)\nanova_coefs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 45 × 5\n   term          estimate std.error statistic  p.value\n   <chr>            <dbl>     <dbl>     <dbl>    <dbl>\n 1 (Intercept)      5732.      529.     10.8  1.34e-19\n 2 n_trtN60         1949.      723.      2.70 8.02e- 3\n 3 n_trtN90         3095.      723.      4.28 3.73e- 5\n 4 n_trtN120        2836.      723.      3.92 1.45e- 4\n 5 n_trtN180        2988.      723.      4.13 6.61e- 5\n 6 n_trtN240        3278.      723.      4.53 1.36e- 5\n 7 n_trtN300        3581.      723.      4.95 2.37e- 6\n 8 siteB           -1659.      723.     -2.29 2.35e- 2\n 9 weathernormal    2132.      723.      2.95 3.83e- 3\n10 weatherwet       1780.      723.      2.46 1.52e- 2\n# ℹ 35 more rows\n```\n\n\n:::\n:::\n\n\n\n\n## How much variance do we explain?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::r2(lm_00)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.000\n  adj. R2: 0.000\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance::r2(lm_01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.351\n  adj. R2: 0.314\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance::r2(lm_02)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.372\n  adj. R2: 0.332\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance::r2(lm_03)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.830\n  adj. R2: 0.818\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance::r2(lm_04)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.851\n  adj. R2: 0.840\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance::r2(lm_05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.944\n  adj. R2: 0.924\n```\n\n\n:::\n:::\n\n\n\n\n:::callout-note\n## Important: do not select models based on R^2^\nR^2^ (and adjusted R^2^) describes the proportion of variance explained *within the fitted dataset*. It almost always increases when you add predictors, even if those predictors are not scientifically meaningful.\n\nWhy this matters:\n\n- R^2^ does not apply a formal penalty for complexity, so it can encourage overfitting.\n- Two models can have very similar R^2^ but very different adequacy (for example, one captures the right structure across site-year, another misses it).\n- In multi-environment agronomy, a high R^2^ can be driven by large mean shifts among environments, while still failing to represent the response process (for example, slope differences, curvature, heteroscedasticity).\n\nUse R^2^ mainly as a descriptive summary (communication), and rely on a combination of scientific objectives, diagnostics, and appropriate comparison criteria (nested tests, AIC/BIC) for selection.\n:::\n\n## A plot that connects model and data\n\nObserved vs fitted plots help you see whether the model is systematically over- or under-predicting within specific environments.\n\nThis is a simple visual way to see how well model prediction works.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_tbl <- cornn_data %>%\n  mutate(fitted_lm01 = predict(lm_01, newdata = cornn_data),\n         fitted_lm05 = predict(lm_05, newdata = cornn_data))\n\n# Model 1\nfit_tbl %>%\n  ggplot(aes(x = yield_kgha/1000, y = fitted_lm01/1000)) +\n  geom_point(alpha = 0.7, size = 2, \n             aes(fill = weather, shape = site)) +\n  geom_abline(intercept = 0, slope = 1) +\n  labs(title = \"Fitted vs. Observed (lm_01 - Pooled)\",\n    x = \"Observed yield (kg/ha)\",\n    y = \"Fitted yield (kg/ha)\")+\n  # Adjust scales\n  scale_shape_manual(values = c(21, 22), name = \"site\") +\n  scale_fill_brewer(palette = \"Set2\", name = \"weather\") +\n  guides( # Adjust legend to show both fill and shape clearly\n    fill  = guide_legend(override.aes = list(shape = 21, color = \"black\")),\n    shape = guide_legend(override.aes = list(fill = \"grey90\")) ) +\n  #facet_grid(site ~ weather) +\n  scale_y_continuous(limits = c(0,18), breaks = seq(0,18,by=2))+\n  scale_x_continuous(limits = c(0,18), breaks = seq(0,18,by=2))+\n  coord_equal()+\n  # Add grid lines for better visibility\n  theme(panel.grid.major = element_line(color = \"gray90\"),\n        panel.grid.minor = element_line(color = \"gray95\"))\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Model 5\nfit_tbl %>%\n  ggplot(aes(x = yield_kgha/1000, y = fitted_lm05/1000)) +\n  geom_point(\n    aes(fill = weather, shape = site),\n    alpha = 0.7, size = 2,\n    color = \"black\", stroke = 0.3\n  ) +\n  geom_abline(intercept = 0, slope = 1) +\n  labs(\n    title = \"Fitted vs. Observed (lm_05 - By site*year)\",\n    x = \"Observed yield (Mg/ha)\",\n    y = \"Fitted yield (Mg/ha)\"\n  ) +\n  scale_shape_manual(values = c(21, 22), name = \"site\") +\n  scale_fill_brewer(palette = \"Set2\", name = \"weather\") +\n  guides( # Adjust legend to show both fill and shape clearly\n    fill  = guide_legend(override.aes = list(shape = 21, color = \"black\")),\n    shape = guide_legend(override.aes = list(fill = \"grey90\")) ) +\n  scale_y_continuous(limits = c(0,18), breaks = seq(0,18,by=2)) +\n  scale_x_continuous(limits = c(0,18), breaks = seq(0,18,by=2)) +\n  coord_equal() +\n  theme(\n    panel.grid.major = element_line(color = \"gray90\"),\n    panel.grid.minor = element_line(color = \"gray95\")\n  )\n```\n\n::: {.cell-output-display}\n![](12_models02_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n:::\n\n\n\n\n:::callout-warning\n## Caution: this is not a predictive model\nThe fitted vs observed plot above is based on the same data used to fit the model, so it is not a true out-of-sample validation. It can show systematic patterns of misfit, but it does not provide an unbiased estimate of predictive performance. For a more rigorous assessment, consider using cross-validation or a separate test dataset.\n:::\n\n## Final comments\n\nLinear models are essential for agricultural research because they provide the simplest framework for estimation and inference (slopes, means, contrasts). In practice, agronomic datasets often require extensions:\n\n- mixed models for random effects (blocks, sites, years)\n- heterogeneous variances and correlation structures\n- non-linear response models for inputs (for example, N response)\n- varying coefficients by environment (site:weather, year)\n\nOn the next modules, we will revisit these same questions with more complex models that may (or not) outperform simple linear models.\n\n## References\n\nAkaike, H. (1974). A new look at the statistical model identification. *IEEE Transactions on Automatic Control*, 19(6), 716–723. https://doi.org/10.1109/TAC.1974.1100705\n\nAnderson, D. R. (2008). *Model based inference in the life sciences: A primer on evidence*. Springer, New York.\n\nBrown, M. B., & Forsythe, A. B. (1974). Robust tests for the equality of variances. *Journal of the American Statistical Association*, 69(346), 364–367. https://doi.org/10.1080/01621459.1974.10482955\n\nBurnham, K. P., & Anderson, D. R. (2002). *Model selection and multimodel inference: A practical information-theoretic approach* (2nd ed.). Springer.\n\nLevene, H. (1960). Robust tests for equality of variances. In I. Olkin (Ed.), *Contributions to probability and statistics: Essays in honor of Harold Hotelling* (pp. 278–292). Stanford University Press.\n\nSchwarz, G. (1978). Estimating the dimension of a model. *The Annals of Statistics*, 6(2), 461–464. https://doi.org/10.1214/aos/1176344136\n\nShapiro, S. S., & Wilk, M. B. (1965). An analysis of variance test for normality (complete samples). *Biometrika*, 52(3–4), 591–611. https://doi.org/10.1093/biomet/52.3-4.591\n\n",
    "supporting": [
      "12_models02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}