---
title: PLNT6530|01 - Calendar
subtitle: "Winter 2026"
author: "Dr. Adrian Correndo"
format:
  html:
    toc: true
    toc-title: 'Contents'
    toc-location: left
    toc-depth: 4
    number-sections: false
    code-tools: true
    code-fold: true
    code-summary: 'Show code'
    code-link: true
highlight-style: pygments
smooth-scroll: true
---

### Lecture Schedule

-   **Days:** Wednesdays and Fridays
-   **Time:** 11:30 am - 12:50 pm
-   **Location:** CRSC 121B

## Calendar

The course runs on Wednesdays and Fridays from 1:00 PM to 2:20 PM. Below is the *tentative* schedule. Please, note the schedule may vary depending on the progress of the class.

| **Week** | **Date** | **Topic** | **Material** | **Lesson** |
|---------------|---------------|---------------|---------------|---------------|
| 1 | Jan 7 | Introductions, Reproducibility | [🌐](https://adriancorrendo.github.io/plnt6530/slides/day1.html) | [🎥](https://zoom.us/rec/share/Dy07MqKf8Lx3VLxAACAzqIXpyB7X4XbhmvZm5tDB9P9quDB4TVwkoMeH2wbAEmqD.kEaLkBlHprEaHDje?startTime=1767803962000) |
|  | Jan 09 | Essentials of Quarto and R | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_01/essentials_01.html) | [🎥](https://zoom.us/rec/share/9pvpNY1H692JIBCaNP6V2O0X_FT7Wk-NNt-XI--9YBxxPRcLq38Uzj0klFyIuCoa.dH46A2XtLbzb1QSN) |
| 2 | Jan 14 | Fundamentals of R packages | [🌐](http://adriancorrendo.github.io/plnt6530/coding/week_02/02_fundamentals_rpackages.html) | [🎥](https://zoom.us/rec/share/ZTz6M5yfomA_H39p4RxZQpWMEfTj3OHqbXGY3Daw7MW6NIIBr7VkMax8VUaPLqSy.bzuwDd7Ci29MpLB2?startTime=1768408473000) |
|  | Jan 16 | Basics of version control & GitHub | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_02/03_versioncontrol.html) | [🎥](https://zoom.us/rec/share/BWba1XKsMaqqqQ5WdM8CVYpCo7wE-nF78oYsHI5VLbjPxxciuu0LdphpU-M6F3ry.IL4B83T_ZqKyA3gQ?startTime=1768581227000) |
| 3 | Jan 21 | Data Wrangling I | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_03/04_datawrangling_01.html) | [🎥](https://zoom.us/rec/share/ZFWzTgRa6e60VNzKXEI7Y8cGUNWtouSGXEcEbpPqVkHFBfr8rh8spcMUZjzyXeUp.YW2Fd8HvscBrhZwx?startTime=1769013287000) |
|  | Jan 23 | Data Wrangling II | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_03/05_datawrangling_02.html) | [🎥](https://zoom.us/rec/share/b4zPnZjJqrU9W8diUrxeVCAnON239CSnsCcd8Ca0o71DTPmif4a1h8dZBQJ3BSrI.ePqnWlUsjhLtp6ii?startTime=1769185854000) |
| 4 | Jan 28 | Data Wrangling III | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_04/06_datawrangling_03.html) | [🎥](https://zoom.us/rec/share/1F4dxjjIrSoybzUVXTMTWPUDIvU8P28rn7X3dvaCyuT_E5B8ZbDblOUVySoCCMlo.CxaSVAad3yVAWwUM?startTime=1769618014000) |
|  | Jan 30 | Data Viz I: ggplot2 basics | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_04/07_ggplot2_01.html) | [🎥](https://zoom.us/rec/share/3q6PHdrPYgi6P1gfqLZXkLFg2yy0GamQDijrx9EP76Fz4aEbSvo5SVN2Hj96EyF1.Ge__6wLoHAPdPr0x?startTime=1769790667000) |
| 5 | Feb 04 | Data Viz II: Multiple plots | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_05/08_ggplot2_adv.html) | [🎥](https://zoom.us/rec/share/DwuC9oy-FTdXZLffC2uKTHbzbhEHAJnXi2EAMlvFZa7UQLHehNoDFcKS8Rm8zp94.n9lhcGt_d_OZggHa?startTime=1770222684000) |
|  | Feb 06 | Data Viz III: Advanced plots, maps | 🌐 | [🎥](https://zoom.us/rec/share/_bcS19dpGf8WB1g4OHBTVWjqQHo_gUMvw4qhTOPHyTOdMxppRxl7KFHNKGILvk6C.dMGRalvSDSSjzD1o?startTime=1770395429000) |
| 6 | Feb 11 | Iteration: Loops & Mapping | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_06/10_iteration.html) | [🎥](https://zoom.us/rec/share/-dw_gRgfxLBbc0Fz0pHHCHlHob-xFXf6eQZEOxEQ89GO_du-X3pVh1oAbUaM8GUX.2wqjUVcfqsWDYHet?startTime=1770827561000) |
|  | Feb 13 | Weather Data: Retrieving & Processing | [🌐](https://adriancorrendo.github.io/plnt6530/coding/extras/weather_data.html) |  |
|  | Feb 13 | Models I: introduction to models | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_06/11_models01.html) | [🎥](https://zoom.us/rec/share/kUkksbCX9bdHB-kLGCibRx6KJnfy_4lVrLd9U3BhAw8PMwP7wGQT8cJTLF96FNzE.WPg6ksgFjWGKYGiR?startTime=1771000876000) |
|  |  | *Winter Break begins after the end of class* |  |  |
| 7 | Feb 25 | Models II: TBD | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_07/12_models02.html) | [🎥](https://zoom.us/rec/share/Ph6ZcOz-9PqmbYJrWgMHH_GWmaO7CqQGPMO266u_27JorGp4WDf6ZgTWq69A9g3m.F5yrajYQ7mdtDpFy?startTime=1772037208000) |
|  | Feb 27 | Models III: TBD | [🌐](https://adriancorrendo.github.io/plnt6530/coding/week_07/13_models03.html) | [🎥](https://zoom.us/rec/share/WxE4td51j9F4AsYRYMEsqYXRR15IciFaCicDXCQpc5R6eVukjWkSWI1M8JoJTYZy.uqgHIe2b6a1ytEvu?startTime=1772209900000) |
| 8 | Mar 04 | Models IV: TBD | 🌐 | 🎥 |
|  | Mar 06 | Models V: TBD | 🌐 | 🎥 |
| 9 | Mar 11 | Models VI: TBD | 🌐 | 🎥 |
|  | Mar 13 | Models VII: TBD | 🌐 | 🎥 |
| 10 | Mar 18 | Models VIII: TBD | 🌐 | 🎥 |
|  | Mar 20 | Models IX: TBD | 🌐 | 🎥 |
| 11 | Mar 25 | Models X: TBD | 🌐 | 🎥 |
|  | Mar 27 | General Review class | 🌐 | 🎥 |
| 12 | Apr 01 | Semester Projects Presentations I | 🌐 |  |
|  | Apr 03 | Semester Projects Presentations II | 🌐 |  |
| 13 | Apr 10 | Final Exam Due (11.59 pm) | 🌐 |  |
